/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinNewslettersRouteImport } from './routes/join-newsletters'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardNewslettersRouteImport } from './routes/_dashboard/newsletters'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCreateCampaignsRouteImport } from './routes/_dashboard/create-campaigns'
import { Route as DashboardContactsRouteImport } from './routes/_dashboard/contacts'
import { Route as DashboardCampaignsRouteImport } from './routes/_dashboard/campaigns'
import { Route as AuthResetpasswordRouteImport } from './routes/_auth/resetpassword'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetpasswordRouteImport } from './routes/_auth/forgetpassword'
import { Route as Auth2faRouteImport } from './routes/_auth/2fa'

const JoinNewslettersRoute = JoinNewslettersRouteImport.update({
  id: '/join-newsletters',
  path: '/join-newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewslettersRoute = DashboardNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateCampaignsRoute =
  DashboardCreateCampaignsRouteImport.update({
    id: '/create-campaigns',
    path: '/create-campaigns',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetpasswordRoute = AuthResetpasswordRouteImport.update({
  id: '/resetpassword',
  path: '/resetpassword',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetpasswordRoute = AuthForgetpasswordRouteImport.update({
  id: '/forgetpassword',
  path: '/forgetpassword',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faRoute = Auth2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/join-newsletters': typeof JoinNewslettersRoute
  '/2fa': typeof Auth2faRoute
  '/forgetpassword': typeof AuthForgetpasswordRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/resetpassword': typeof AuthResetpasswordRoute
  '/campaigns': typeof DashboardCampaignsRoute
  '/contacts': typeof DashboardContactsRoute
  '/create-campaigns': typeof DashboardCreateCampaignsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/newsletters': typeof DashboardNewslettersRoute
  '/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesByTo {
  '/join-newsletters': typeof JoinNewslettersRoute
  '/2fa': typeof Auth2faRoute
  '/forgetpassword': typeof AuthForgetpasswordRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/resetpassword': typeof AuthResetpasswordRoute
  '/campaigns': typeof DashboardCampaignsRoute
  '/contacts': typeof DashboardContactsRoute
  '/create-campaigns': typeof DashboardCreateCampaignsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/newsletters': typeof DashboardNewslettersRoute
  '/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/join-newsletters': typeof JoinNewslettersRoute
  '/_auth/2fa': typeof Auth2faRoute
  '/_auth/forgetpassword': typeof AuthForgetpasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/resetpassword': typeof AuthResetpasswordRoute
  '/_dashboard/campaigns': typeof DashboardCampaignsRoute
  '/_dashboard/contacts': typeof DashboardContactsRoute
  '/_dashboard/create-campaigns': typeof DashboardCreateCampaignsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/newsletters': typeof DashboardNewslettersRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join-newsletters'
    | '/2fa'
    | '/forgetpassword'
    | '/login'
    | '/otp'
    | '/resetpassword'
    | '/campaigns'
    | '/contacts'
    | '/create-campaigns'
    | '/dashboard'
    | '/newsletters'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join-newsletters'
    | '/2fa'
    | '/forgetpassword'
    | '/login'
    | '/otp'
    | '/resetpassword'
    | '/campaigns'
    | '/contacts'
    | '/create-campaigns'
    | '/dashboard'
    | '/newsletters'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/join-newsletters'
    | '/_auth/2fa'
    | '/_auth/forgetpassword'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/resetpassword'
    | '/_dashboard/campaigns'
    | '/_dashboard/contacts'
    | '/_dashboard/create-campaigns'
    | '/_dashboard/dashboard'
    | '/_dashboard/newsletters'
    | '/_dashboard/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  JoinNewslettersRoute: typeof JoinNewslettersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-newsletters': {
      id: '/join-newsletters'
      path: '/join-newsletters'
      fullPath: '/join-newsletters'
      preLoaderRoute: typeof JoinNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/newsletters': {
      id: '/_dashboard/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof DashboardNewslettersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/create-campaigns': {
      id: '/_dashboard/create-campaigns'
      path: '/create-campaigns'
      fullPath: '/create-campaigns'
      preLoaderRoute: typeof DashboardCreateCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contacts': {
      id: '/_dashboard/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/campaigns': {
      id: '/_dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/resetpassword': {
      id: '/_auth/resetpassword'
      path: '/resetpassword'
      fullPath: '/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgetpassword': {
      id: '/_auth/forgetpassword'
      path: '/forgetpassword'
      fullPath: '/forgetpassword'
      preLoaderRoute: typeof AuthForgetpasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/2fa': {
      id: '/_auth/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof Auth2faRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  Auth2faRoute: typeof Auth2faRoute
  AuthForgetpasswordRoute: typeof AuthForgetpasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faRoute: Auth2faRoute,
  AuthForgetpasswordRoute: AuthForgetpasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardCreateCampaignsRoute: typeof DashboardCreateCampaignsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardNewslettersRoute: typeof DashboardNewslettersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardCreateCampaignsRoute: DashboardCreateCampaignsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardNewslettersRoute: DashboardNewslettersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  JoinNewslettersRoute: JoinNewslettersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
